//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetSoapReport
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MovimientoDetalleDTO", Namespace= "http://schemas.datacontract.org/2004/07/EurekaBank_Soap_DotNet_GR05.Models.DTOs")]
    public partial class MovimientoDetalleDTO : object
    {
        
        private string AccionField;
        
        private string CodigoCuentaField;
        
        private string CuentaReferenciaField;
        
        private string EmpleadoNombreField;
        
        private System.DateTime FechaField;
        
        private decimal ImporteField;
        
        private int NumeroMovimientoField;
        
        private string TipoMovimientoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Accion
        {
            get
            {
                return this.AccionField;
            }
            set
            {
                this.AccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoCuenta
        {
            get
            {
                return this.CodigoCuentaField;
            }
            set
            {
                this.CodigoCuentaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CuentaReferencia
        {
            get
            {
                return this.CuentaReferenciaField;
            }
            set
            {
                this.CuentaReferenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpleadoNombre
        {
            get
            {
                return this.EmpleadoNombreField;
            }
            set
            {
                this.EmpleadoNombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha
        {
            get
            {
                return this.FechaField;
            }
            set
            {
                this.FechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Importe
        {
            get
            {
                return this.ImporteField;
            }
            set
            {
                this.ImporteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroMovimiento
        {
            get
            {
                return this.NumeroMovimientoField;
            }
            set
            {
                this.NumeroMovimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoMovimiento
        {
            get
            {
                return this.TipoMovimientoField;
            }
            set
            {
                this.TipoMovimientoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DotNetSoapReport.IServicioReporte")]
    public interface IServicioReporte
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReporte/ObtenerMovimientos", ReplyAction="http://tempuri.org/IServicioReporte/ObtenerMovimientosResponse")]
        System.Threading.Tasks.Task<DotNetSoapReport.MovimientoDetalleDTO[]> ObtenerMovimientosAsync(string codigoCuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReporte/ObtenerMovimientosPorRango", ReplyAction="http://tempuri.org/IServicioReporte/ObtenerMovimientosPorRangoResponse")]
        System.Threading.Tasks.Task<DotNetSoapReport.MovimientoDetalleDTO[]> ObtenerMovimientosPorRangoAsync(string codigoCuenta, System.DateTime fechaInicio, System.DateTime fechaFin);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IServicioReporteChannel : DotNetSoapReport.IServicioReporte, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ServicioReporteClient : System.ServiceModel.ClientBase<DotNetSoapReport.IServicioReporte>, DotNetSoapReport.IServicioReporte
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioReporteClient() : 
                base(ServicioReporteClient.GetDefaultBinding(), ServicioReporteClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioReporte.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioReporteClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioReporteClient.GetBindingForEndpoint(endpointConfiguration), ServicioReporteClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioReporteClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioReporteClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioReporteClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioReporteClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioReporteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<DotNetSoapReport.MovimientoDetalleDTO[]> ObtenerMovimientosAsync(string codigoCuenta)
        {
            return base.Channel.ObtenerMovimientosAsync(codigoCuenta);
        }
        
        public System.Threading.Tasks.Task<DotNetSoapReport.MovimientoDetalleDTO[]> ObtenerMovimientosPorRangoAsync(string codigoCuenta, System.DateTime fechaInicio, System.DateTime fechaFin)
        {
            return base.Channel.ObtenerMovimientosPorRangoAsync(codigoCuenta, fechaInicio, fechaFin);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioReporte))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioReporte))
            {
                return new System.ServiceModel.EndpointAddress("http://10.40.16.33:8004/ws/ServicioReporte.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioReporteClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioReporte);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioReporteClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioReporte);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioReporte,
        }
    }
}
