//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JavaSoapAuth
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.monster.edu.ec/", ConfigurationName="JavaSoapAuth.ServicioAutenticacion")]
    public interface ServicioAutenticacion
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.monster.edu.ec/ServicioAutenticacion/loginRequest", ReplyAction="http://ws.monster.edu.ec/ServicioAutenticacion/loginResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(loginResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(login))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registrarEmpleadoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registrarEmpleado))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(cambiarClaveResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(cambiarClave))]
        System.Threading.Tasks.Task<JavaSoapAuth.loginResponse1> loginAsync(JavaSoapAuth.loginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.monster.edu.ec/ServicioAutenticacion/registrarEmpleadoRequest", ReplyAction="http://ws.monster.edu.ec/ServicioAutenticacion/registrarEmpleadoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(loginResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(login))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registrarEmpleadoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registrarEmpleado))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(cambiarClaveResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(cambiarClave))]
        System.Threading.Tasks.Task<JavaSoapAuth.registrarEmpleadoResponse1> registrarEmpleadoAsync(JavaSoapAuth.registrarEmpleadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.monster.edu.ec/ServicioAutenticacion/cambiarClaveRequest", ReplyAction="http://ws.monster.edu.ec/ServicioAutenticacion/cambiarClaveResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(loginResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(login))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registrarEmpleadoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registrarEmpleado))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(cambiarClaveResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(cambiarClave))]
        System.Threading.Tasks.Task<JavaSoapAuth.cambiarClaveResponse1> cambiarClaveAsync(JavaSoapAuth.cambiarClaveRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.monster.edu.ec/")]
    public partial class respuestaDTO
    {
        
        private string codigoErrorField;
        
        private object datosField;
        
        private bool exitosoField;
        
        private string mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoError
        {
            get
            {
                return this.codigoErrorField;
            }
            set
            {
                this.codigoErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public object datos
        {
            get
            {
                return this.datosField;
            }
            set
            {
                this.datosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool exitoso
        {
            get
            {
                return this.exitosoField;
            }
            set
            {
                this.exitosoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.monster.edu.ec/")]
    public partial class loginResponse
    {
        
        private respuestaDTO returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public respuestaDTO @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.monster.edu.ec/")]
    public partial class login
    {
        
        private string usuarioField;
        
        private string claveField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string usuario
        {
            get
            {
                return this.usuarioField;
            }
            set
            {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string clave
        {
            get
            {
                return this.claveField;
            }
            set
            {
                this.claveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.monster.edu.ec/")]
    public partial class registrarEmpleadoResponse
    {
        
        private respuestaDTO returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public respuestaDTO @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.monster.edu.ec/")]
    public partial class empleado
    {
        
        private string ciudadField;
        
        private string claveField;
        
        private string codigoField;
        
        private string direccionField;
        
        private string maternoField;
        
        private string nombreField;
        
        private string paternoField;
        
        private string usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ciudad
        {
            get
            {
                return this.ciudadField;
            }
            set
            {
                this.ciudadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string clave
        {
            get
            {
                return this.claveField;
            }
            set
            {
                this.claveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string direccion
        {
            get
            {
                return this.direccionField;
            }
            set
            {
                this.direccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string materno
        {
            get
            {
                return this.maternoField;
            }
            set
            {
                this.maternoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string paterno
        {
            get
            {
                return this.paternoField;
            }
            set
            {
                this.paternoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string usuario
        {
            get
            {
                return this.usuarioField;
            }
            set
            {
                this.usuarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.monster.edu.ec/")]
    public partial class registrarEmpleado
    {
        
        private empleado empleadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public empleado empleado
        {
            get
            {
                return this.empleadoField;
            }
            set
            {
                this.empleadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.monster.edu.ec/")]
    public partial class cambiarClaveResponse
    {
        
        private respuestaDTO returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public respuestaDTO @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.monster.edu.ec/")]
    public partial class cambiarClave
    {
        
        private string codigoField;
        
        private string claveActualField;
        
        private string claveNuevaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string claveActual
        {
            get
            {
                return this.claveActualField;
            }
            set
            {
                this.claveActualField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string claveNueva
        {
            get
            {
                return this.claveNuevaField;
            }
            set
            {
                this.claveNuevaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="login", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class loginRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clave;
        
        public loginRequest()
        {
        }
        
        public loginRequest(string usuario, string clave)
        {
            this.usuario = usuario;
            this.clave = clave;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loginResponse", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class loginResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public JavaSoapAuth.respuestaDTO @return;
        
        public loginResponse1()
        {
        }
        
        public loginResponse1(JavaSoapAuth.respuestaDTO @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarEmpleado", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class registrarEmpleadoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public JavaSoapAuth.empleado empleado;
        
        public registrarEmpleadoRequest()
        {
        }
        
        public registrarEmpleadoRequest(JavaSoapAuth.empleado empleado)
        {
            this.empleado = empleado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarEmpleadoResponse", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class registrarEmpleadoResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public JavaSoapAuth.respuestaDTO @return;
        
        public registrarEmpleadoResponse1()
        {
        }
        
        public registrarEmpleadoResponse1(JavaSoapAuth.respuestaDTO @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cambiarClave", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class cambiarClaveRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string claveActual;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string claveNueva;
        
        public cambiarClaveRequest()
        {
        }
        
        public cambiarClaveRequest(string codigo, string claveActual, string claveNueva)
        {
            this.codigo = codigo;
            this.claveActual = claveActual;
            this.claveNueva = claveNueva;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cambiarClaveResponse", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class cambiarClaveResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public JavaSoapAuth.respuestaDTO @return;
        
        public cambiarClaveResponse1()
        {
        }
        
        public cambiarClaveResponse1(JavaSoapAuth.respuestaDTO @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ServicioAutenticacionChannel : JavaSoapAuth.ServicioAutenticacion, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ServicioAutenticacionClient : System.ServiceModel.ClientBase<JavaSoapAuth.ServicioAutenticacion>, JavaSoapAuth.ServicioAutenticacion
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioAutenticacionClient() : 
                base(ServicioAutenticacionClient.GetDefaultBinding(), ServicioAutenticacionClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ServicioAutenticacionPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioAutenticacionClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioAutenticacionClient.GetBindingForEndpoint(endpointConfiguration), ServicioAutenticacionClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioAutenticacionClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioAutenticacionClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioAutenticacionClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioAutenticacionClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioAutenticacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JavaSoapAuth.loginResponse1> JavaSoapAuth.ServicioAutenticacion.loginAsync(JavaSoapAuth.loginRequest request)
        {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<JavaSoapAuth.loginResponse1> loginAsync(string usuario, string clave)
        {
            JavaSoapAuth.loginRequest inValue = new JavaSoapAuth.loginRequest();
            inValue.usuario = usuario;
            inValue.clave = clave;
            return ((JavaSoapAuth.ServicioAutenticacion)(this)).loginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JavaSoapAuth.registrarEmpleadoResponse1> JavaSoapAuth.ServicioAutenticacion.registrarEmpleadoAsync(JavaSoapAuth.registrarEmpleadoRequest request)
        {
            return base.Channel.registrarEmpleadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<JavaSoapAuth.registrarEmpleadoResponse1> registrarEmpleadoAsync(JavaSoapAuth.empleado empleado)
        {
            JavaSoapAuth.registrarEmpleadoRequest inValue = new JavaSoapAuth.registrarEmpleadoRequest();
            inValue.empleado = empleado;
            return ((JavaSoapAuth.ServicioAutenticacion)(this)).registrarEmpleadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JavaSoapAuth.cambiarClaveResponse1> JavaSoapAuth.ServicioAutenticacion.cambiarClaveAsync(JavaSoapAuth.cambiarClaveRequest request)
        {
            return base.Channel.cambiarClaveAsync(request);
        }
        
        public System.Threading.Tasks.Task<JavaSoapAuth.cambiarClaveResponse1> cambiarClaveAsync(string codigo, string claveActual, string claveNueva)
        {
            JavaSoapAuth.cambiarClaveRequest inValue = new JavaSoapAuth.cambiarClaveRequest();
            inValue.codigo = codigo;
            inValue.claveActual = claveActual;
            inValue.claveNueva = claveNueva;
            return ((JavaSoapAuth.ServicioAutenticacion)(this)).cambiarClaveAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServicioAutenticacionPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServicioAutenticacionPort))
            {
                return new System.ServiceModel.EndpointAddress("http://10.40.16.33:8080/EurekaBank_Soap_Java_GR01/ServicioAutenticacion");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioAutenticacionClient.GetBindingForEndpoint(EndpointConfiguration.ServicioAutenticacionPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioAutenticacionClient.GetEndpointAddress(EndpointConfiguration.ServicioAutenticacionPort);
        }
        
        public enum EndpointConfiguration
        {
            
            ServicioAutenticacionPort,
        }
    }
}
