//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml;

namespace JavaSoapTransaction
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.monster.edu.ec/", ConfigurationName="JavaSoapTransaction.ServicioTransaccion")]
    public interface ServicioTransaccion
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.monster.edu.ec/ServicioTransaccion/realizarDepositoRequest", ReplyAction="http://ws.monster.edu.ec/ServicioTransaccion/realizarDepositoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(realizarDepositoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(realizarDeposito))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(realizarTransferenciaResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(realizarTransferencia))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(realizarRetiroResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(realizarRetiro))]
        System.Threading.Tasks.Task<JavaSoapTransaction.realizarDepositoResponse1> realizarDepositoAsync(JavaSoapTransaction.realizarDepositoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.monster.edu.ec/ServicioTransaccion/realizarRetiroRequest", ReplyAction="http://ws.monster.edu.ec/ServicioTransaccion/realizarRetiroResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(realizarDepositoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(realizarDeposito))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(realizarTransferenciaResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(realizarTransferencia))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(realizarRetiroResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(realizarRetiro))]
        System.Threading.Tasks.Task<JavaSoapTransaction.realizarRetiroResponse1> realizarRetiroAsync(JavaSoapTransaction.realizarRetiroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.monster.edu.ec/ServicioTransaccion/realizarTransferenciaRequest", ReplyAction="http://ws.monster.edu.ec/ServicioTransaccion/realizarTransferenciaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(realizarDepositoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(realizarDeposito))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(realizarTransferenciaResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(realizarTransferencia))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(realizarRetiroResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(realizarRetiro))]
        System.Threading.Tasks.Task<JavaSoapTransaction.realizarTransferenciaResponse1> realizarTransferenciaAsync(JavaSoapTransaction.realizarTransferenciaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.monster.edu.ec/")]
    public partial class transaccionDTO
    {
        
        private string claveCuentaField;
        
        private string codigoCuentaField;
        
        private string codigoEmpleadoField;
        
        private string codigoTipoMovimientoField;
        
        private decimal importeField;
        
        private bool importeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string claveCuenta
        {
            get
            {
                return this.claveCuentaField;
            }
            set
            {
                this.claveCuentaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codigoCuenta
        {
            get
            {
                return this.codigoCuentaField;
            }
            set
            {
                this.codigoCuentaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string codigoEmpleado
        {
            get
            {
                return this.codigoEmpleadoField;
            }
            set
            {
                this.codigoEmpleadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string codigoTipoMovimiento
        {
            get
            {
                return this.codigoTipoMovimientoField;
            }
            set
            {
                this.codigoTipoMovimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal importe
        {
            get
            {
                return this.importeField;
            }
            set
            {
                this.importeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool importeSpecified
        {
            get
            {
                return this.importeFieldSpecified;
            }
            set
            {
                this.importeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.monster.edu.ec/")]
    public partial class realizarDepositoResponse
    {
        
        private respuestaDTO returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public respuestaDTO @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.monster.edu.ec/")]
    public partial class respuestaDTO
    {
        
        private string codigoErrorField;

        private XmlElement datosField;
        private bool exitosoField;
        
        private string mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoError
        {
            get
            {
                return this.codigoErrorField;
            }
            set
            {
                this.codigoErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public XmlElement datos // <-- CAMBIO DE TIPO
        {
            get { return this.datosField; }
            set { this.datosField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool exitoso
        {
            get
            {
                return this.exitosoField;
            }
            set
            {
                this.exitosoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.monster.edu.ec/")]
    public partial class realizarDeposito
    {
        
        private transaccionDTO datosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public transaccionDTO datos
        {
            get
            {
                return this.datosField;
            }
            set
            {
                this.datosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.monster.edu.ec/")]
    public partial class realizarTransferenciaResponse
    {
        
        private respuestaDTO returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public respuestaDTO @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.monster.edu.ec/")]
    public partial class transferenciaDTO
    {
        
        private string claveCuentaOrigenField;
        
        private string codigoEmpleadoField;
        
        private string cuentaDestinoField;
        
        private string cuentaOrigenField;
        
        private decimal importeField;
        
        private bool importeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string claveCuentaOrigen
        {
            get
            {
                return this.claveCuentaOrigenField;
            }
            set
            {
                this.claveCuentaOrigenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codigoEmpleado
        {
            get
            {
                return this.codigoEmpleadoField;
            }
            set
            {
                this.codigoEmpleadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string cuentaDestino
        {
            get
            {
                return this.cuentaDestinoField;
            }
            set
            {
                this.cuentaDestinoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string cuentaOrigen
        {
            get
            {
                return this.cuentaOrigenField;
            }
            set
            {
                this.cuentaOrigenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal importe
        {
            get
            {
                return this.importeField;
            }
            set
            {
                this.importeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool importeSpecified
        {
            get
            {
                return this.importeFieldSpecified;
            }
            set
            {
                this.importeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.monster.edu.ec/")]
    public partial class realizarTransferencia
    {
        
        private transferenciaDTO datosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public transferenciaDTO datos
        {
            get
            {
                return this.datosField;
            }
            set
            {
                this.datosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.monster.edu.ec/")]
    public partial class realizarRetiroResponse
    {
        
        private respuestaDTO returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public respuestaDTO @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.monster.edu.ec/")]
    public partial class realizarRetiro
    {
        
        private transaccionDTO datosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public transaccionDTO datos
        {
            get
            {
                return this.datosField;
            }
            set
            {
                this.datosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="realizarDeposito", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class realizarDepositoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public JavaSoapTransaction.transaccionDTO datos;
        
        public realizarDepositoRequest()
        {
        }
        
        public realizarDepositoRequest(JavaSoapTransaction.transaccionDTO datos)
        {
            this.datos = datos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="realizarDepositoResponse", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class realizarDepositoResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public JavaSoapTransaction.respuestaDTO @return;
        
        public realizarDepositoResponse1()
        {
        }
        
        public realizarDepositoResponse1(JavaSoapTransaction.respuestaDTO @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="realizarRetiro", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class realizarRetiroRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public JavaSoapTransaction.transaccionDTO datos;
        
        public realizarRetiroRequest()
        {
        }
        
        public realizarRetiroRequest(JavaSoapTransaction.transaccionDTO datos)
        {
            this.datos = datos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="realizarRetiroResponse", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class realizarRetiroResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public JavaSoapTransaction.respuestaDTO @return;
        
        public realizarRetiroResponse1()
        {
        }
        
        public realizarRetiroResponse1(JavaSoapTransaction.respuestaDTO @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="realizarTransferencia", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class realizarTransferenciaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public JavaSoapTransaction.transferenciaDTO datos;
        
        public realizarTransferenciaRequest()
        {
        }
        
        public realizarTransferenciaRequest(JavaSoapTransaction.transferenciaDTO datos)
        {
            this.datos = datos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="realizarTransferenciaResponse", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class realizarTransferenciaResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public JavaSoapTransaction.respuestaDTO @return;
        
        public realizarTransferenciaResponse1()
        {
        }
        
        public realizarTransferenciaResponse1(JavaSoapTransaction.respuestaDTO @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ServicioTransaccionChannel : JavaSoapTransaction.ServicioTransaccion, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ServicioTransaccionClient : System.ServiceModel.ClientBase<JavaSoapTransaction.ServicioTransaccion>, JavaSoapTransaction.ServicioTransaccion
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioTransaccionClient() : 
                base(ServicioTransaccionClient.GetDefaultBinding(), ServicioTransaccionClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ServicioTransaccionPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioTransaccionClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioTransaccionClient.GetBindingForEndpoint(endpointConfiguration), ServicioTransaccionClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioTransaccionClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioTransaccionClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioTransaccionClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioTransaccionClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioTransaccionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JavaSoapTransaction.realizarDepositoResponse1> JavaSoapTransaction.ServicioTransaccion.realizarDepositoAsync(JavaSoapTransaction.realizarDepositoRequest request)
        {
            return base.Channel.realizarDepositoAsync(request);
        }
        
        public System.Threading.Tasks.Task<JavaSoapTransaction.realizarDepositoResponse1> realizarDepositoAsync(JavaSoapTransaction.transaccionDTO datos)
        {
            JavaSoapTransaction.realizarDepositoRequest inValue = new JavaSoapTransaction.realizarDepositoRequest();
            inValue.datos = datos;
            return ((JavaSoapTransaction.ServicioTransaccion)(this)).realizarDepositoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JavaSoapTransaction.realizarRetiroResponse1> JavaSoapTransaction.ServicioTransaccion.realizarRetiroAsync(JavaSoapTransaction.realizarRetiroRequest request)
        {
            return base.Channel.realizarRetiroAsync(request);
        }
        
        public System.Threading.Tasks.Task<JavaSoapTransaction.realizarRetiroResponse1> realizarRetiroAsync(JavaSoapTransaction.transaccionDTO datos)
        {
            JavaSoapTransaction.realizarRetiroRequest inValue = new JavaSoapTransaction.realizarRetiroRequest();
            inValue.datos = datos;
            return ((JavaSoapTransaction.ServicioTransaccion)(this)).realizarRetiroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JavaSoapTransaction.realizarTransferenciaResponse1> JavaSoapTransaction.ServicioTransaccion.realizarTransferenciaAsync(JavaSoapTransaction.realizarTransferenciaRequest request)
        {
            return base.Channel.realizarTransferenciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<JavaSoapTransaction.realizarTransferenciaResponse1> realizarTransferenciaAsync(JavaSoapTransaction.transferenciaDTO datos)
        {
            JavaSoapTransaction.realizarTransferenciaRequest inValue = new JavaSoapTransaction.realizarTransferenciaRequest();
            inValue.datos = datos;
            return ((JavaSoapTransaction.ServicioTransaccion)(this)).realizarTransferenciaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServicioTransaccionPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServicioTransaccionPort))
            {
                return new System.ServiceModel.EndpointAddress("http://10.40.16.33:8080/EurekaBank_Soap_Java_GR01/ServicioTransaccion");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioTransaccionClient.GetBindingForEndpoint(EndpointConfiguration.ServicioTransaccionPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioTransaccionClient.GetEndpointAddress(EndpointConfiguration.ServicioTransaccionPort);
        }
        
        public enum EndpointConfiguration
        {
            
            ServicioTransaccionPort,
        }
    }
}
