//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JavaSoapReport
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.monster.edu.ec/", ConfigurationName="JavaSoapReport.ServicioReporte")]
    public interface ServicioReporte
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.monster.edu.ec/ServicioReporte/obtenerMovimientosRequest", ReplyAction="http://ws.monster.edu.ec/ServicioReporte/obtenerMovimientosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<JavaSoapReport.obtenerMovimientosResponse> obtenerMovimientosAsync(JavaSoapReport.obtenerMovimientosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.monster.edu.ec/ServicioReporte/obtenerMovimientosPorRangoRequest", ReplyAction="http://ws.monster.edu.ec/ServicioReporte/obtenerMovimientosPorRangoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<JavaSoapReport.obtenerMovimientosPorRangoResponse> obtenerMovimientosPorRangoAsync(JavaSoapReport.obtenerMovimientosPorRangoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.monster.edu.ec/")]
    public partial class movimientoDetalleDTO
    {
        
        private string accionField;
        
        private string codigoCuentaField;
        
        private string cuentaReferenciaField;
        
        private string empleadoNombreField;
        
        private localDate fechaField;
        
        private decimal importeField;
        
        private bool importeFieldSpecified;
        
        private int numeroMovimientoField;
        
        private string tipoMovimientoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string accion
        {
            get
            {
                return this.accionField;
            }
            set
            {
                this.accionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codigoCuenta
        {
            get
            {
                return this.codigoCuentaField;
            }
            set
            {
                this.codigoCuentaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string cuentaReferencia
        {
            get
            {
                return this.cuentaReferenciaField;
            }
            set
            {
                this.cuentaReferenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string empleadoNombre
        {
            get
            {
                return this.empleadoNombreField;
            }
            set
            {
                this.empleadoNombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public localDate fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal importe
        {
            get
            {
                return this.importeField;
            }
            set
            {
                this.importeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool importeSpecified
        {
            get
            {
                return this.importeFieldSpecified;
            }
            set
            {
                this.importeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int numeroMovimiento
        {
            get
            {
                return this.numeroMovimientoField;
            }
            set
            {
                this.numeroMovimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string tipoMovimiento
        {
            get
            {
                return this.tipoMovimientoField;
            }
            set
            {
                this.tipoMovimientoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.monster.edu.ec/")]
    public partial class localDate
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerMovimientos", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class obtenerMovimientosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoCuenta;
        
        public obtenerMovimientosRequest()
        {
        }
        
        public obtenerMovimientosRequest(string codigoCuenta)
        {
            this.codigoCuenta = codigoCuenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerMovimientosResponse", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class obtenerMovimientosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public JavaSoapReport.movimientoDetalleDTO[] @return;
        private JavaSoapReport.movimientoDetalleDTO[] returnField;

        public obtenerMovimientosResponse()
        {
        }
        
        public obtenerMovimientosResponse(JavaSoapReport.movimientoDetalleDTO[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerMovimientosPorRango", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class obtenerMovimientosPorRangoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoCuenta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fechaInicio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fechaFin;
        
        public obtenerMovimientosPorRangoRequest()
        {
        }
        
        public obtenerMovimientosPorRangoRequest(string codigoCuenta, string fechaInicio, string fechaFin)
        {
            this.codigoCuenta = codigoCuenta;
            this.fechaInicio = fechaInicio;
            this.fechaFin = fechaFin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerMovimientosPorRangoResponse", WrapperNamespace="http://ws.monster.edu.ec/", IsWrapped=true)]
    public partial class obtenerMovimientosPorRangoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.monster.edu.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public JavaSoapReport.movimientoDetalleDTO[] @return;
        
        public obtenerMovimientosPorRangoResponse()
        {
        }
        
        public obtenerMovimientosPorRangoResponse(JavaSoapReport.movimientoDetalleDTO[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ServicioReporteChannel : JavaSoapReport.ServicioReporte, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ServicioReporteClient : System.ServiceModel.ClientBase<JavaSoapReport.ServicioReporte>, JavaSoapReport.ServicioReporte
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioReporteClient() : 
                base(ServicioReporteClient.GetDefaultBinding(), ServicioReporteClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ServicioReportePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioReporteClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioReporteClient.GetBindingForEndpoint(endpointConfiguration), ServicioReporteClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioReporteClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioReporteClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioReporteClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioReporteClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioReporteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JavaSoapReport.obtenerMovimientosResponse> JavaSoapReport.ServicioReporte.obtenerMovimientosAsync(JavaSoapReport.obtenerMovimientosRequest request)
        {
            return base.Channel.obtenerMovimientosAsync(request);
        }
        
        public System.Threading.Tasks.Task<JavaSoapReport.obtenerMovimientosResponse> obtenerMovimientosAsync(string codigoCuenta)
        {
            JavaSoapReport.obtenerMovimientosRequest inValue = new JavaSoapReport.obtenerMovimientosRequest();
            inValue.codigoCuenta = codigoCuenta;
            return ((JavaSoapReport.ServicioReporte)(this)).obtenerMovimientosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JavaSoapReport.obtenerMovimientosPorRangoResponse> JavaSoapReport.ServicioReporte.obtenerMovimientosPorRangoAsync(JavaSoapReport.obtenerMovimientosPorRangoRequest request)
        {
            return base.Channel.obtenerMovimientosPorRangoAsync(request);
        }
        
        public System.Threading.Tasks.Task<JavaSoapReport.obtenerMovimientosPorRangoResponse> obtenerMovimientosPorRangoAsync(string codigoCuenta, string fechaInicio, string fechaFin)
        {
            JavaSoapReport.obtenerMovimientosPorRangoRequest inValue = new JavaSoapReport.obtenerMovimientosPorRangoRequest();
            inValue.codigoCuenta = codigoCuenta;
            inValue.fechaInicio = fechaInicio;
            inValue.fechaFin = fechaFin;
            return ((JavaSoapReport.ServicioReporte)(this)).obtenerMovimientosPorRangoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServicioReportePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServicioReportePort))
            {
                return new System.ServiceModel.EndpointAddress("http://10.40.16.33:8080/EurekaBank_Soap_Java_GR01/ServicioReporte");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioReporteClient.GetBindingForEndpoint(EndpointConfiguration.ServicioReportePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioReporteClient.GetEndpointAddress(EndpointConfiguration.ServicioReportePort);
        }
        
        public enum EndpointConfiguration
        {
            
            ServicioReportePort,
        }
    }
}
