//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetSoapTransaction
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransaccionDTO", Namespace= "http://schemas.datacontract.org/2004/07/EurekaBank_Soap_DotNet_GR05.Models.DTOs")]
    public partial class TransaccionDTO : object
    {
        
        private string ClaveCuentaField;
        
        private string CodigoCuentaField;
        
        private string CodigoEmpleadoField;
        
        private string CodigoTipoMovimientoField;
        
        private decimal ImporteField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaveCuenta
        {
            get
            {
                return this.ClaveCuentaField;
            }
            set
            {
                this.ClaveCuentaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoCuenta
        {
            get
            {
                return this.CodigoCuentaField;
            }
            set
            {
                this.CodigoCuentaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoEmpleado
        {
            get
            {
                return this.CodigoEmpleadoField;
            }
            set
            {
                this.CodigoEmpleadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoTipoMovimiento
        {
            get
            {
                return this.CodigoTipoMovimientoField;
            }
            set
            {
                this.CodigoTipoMovimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Importe
        {
            get
            {
                return this.ImporteField;
            }
            set
            {
                this.ImporteField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaDTO", Namespace= "http://schemas.datacontract.org/2004/07/EurekaBank_Soap_DotNet_GR05.Models.DTOs")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DotNetSoapTransaction.Empleado))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DotNetSoapTransaction.Cliente))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DotNetSoapTransaction.Cuenta))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DotNetSoapTransaction.TransaccionDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DotNetSoapTransaction.DepositoResultDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DotNetSoapTransaction.RetiroResultDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DotNetSoapTransaction.TransferenciaResultDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DotNetSoapTransaction.CuentaResumenDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DotNetSoapTransaction.TransferenciaDTO))]
    public partial class RespuestaDTO : object
    {
        
        private string CodigoErrorField;
        
        private object DatosField;
        
        private bool ExitosoField;
        
        private string MensajeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoError
        {
            get
            {
                return this.CodigoErrorField;
            }
            set
            {
                this.CodigoErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Datos
        {
            get
            {
                return this.DatosField;
            }
            set
            {
                this.DatosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Exitoso
        {
            get
            {
                return this.ExitosoField;
            }
            set
            {
                this.ExitosoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empleado", Namespace= "http://schemas.datacontract.org/2004/07/EurekaBank_Soap_DotNet_GR05.Models")]
    public partial class Empleado : object
    {
        
        private string CiudadField;
        
        private string ClaveField;
        
        private string CodigoField;
        
        private string DireccionField;
        
        private string MaternoField;
        
        private string NombreField;
        
        private string PaternoField;
        
        private string UsuarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ciudad
        {
            get
            {
                return this.CiudadField;
            }
            set
            {
                this.CiudadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Clave
        {
            get
            {
                return this.ClaveField;
            }
            set
            {
                this.ClaveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion
        {
            get
            {
                return this.DireccionField;
            }
            set
            {
                this.DireccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Materno
        {
            get
            {
                return this.MaternoField;
            }
            set
            {
                this.MaternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Paterno
        {
            get
            {
                return this.PaternoField;
            }
            set
            {
                this.PaternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario
        {
            get
            {
                return this.UsuarioField;
            }
            set
            {
                this.UsuarioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace= "http://schemas.datacontract.org/2004/07/EurekaBank_Soap_DotNet_GR05.Models")]
    public partial class Cliente : object
    {
        
        private string CiudadField;
        
        private string CodigoField;
        
        private string DNIField;
        
        private string DireccionField;
        
        private string EmailField;
        
        private string MaternoField;
        
        private string NombreField;
        
        private string PaternoField;
        
        private string TelefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ciudad
        {
            get
            {
                return this.CiudadField;
            }
            set
            {
                this.CiudadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DNI
        {
            get
            {
                return this.DNIField;
            }
            set
            {
                this.DNIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion
        {
            get
            {
                return this.DireccionField;
            }
            set
            {
                this.DireccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Materno
        {
            get
            {
                return this.MaternoField;
            }
            set
            {
                this.MaternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Paterno
        {
            get
            {
                return this.PaternoField;
            }
            set
            {
                this.PaternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cuenta", Namespace= "http://schemas.datacontract.org/2004/07/EurekaBank_Soap_DotNet_GR05.Models")]
    public partial class Cuenta : object
    {
        
        private string ClaveField;
        
        private string CodigoField;
        
        private string CodigoClienteField;
        
        private string CodigoEmpleadoCreadorField;
        
        private string CodigoMonedaField;
        
        private string CodigoSucursalField;
        
        private int ContadorMovimientosField;
        
        private string EstadoField;
        
        private System.DateTime FechaCreacionField;
        
        private decimal SaldoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Clave
        {
            get
            {
                return this.ClaveField;
            }
            set
            {
                this.ClaveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoCliente
        {
            get
            {
                return this.CodigoClienteField;
            }
            set
            {
                this.CodigoClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoEmpleadoCreador
        {
            get
            {
                return this.CodigoEmpleadoCreadorField;
            }
            set
            {
                this.CodigoEmpleadoCreadorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoMoneda
        {
            get
            {
                return this.CodigoMonedaField;
            }
            set
            {
                this.CodigoMonedaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoSucursal
        {
            get
            {
                return this.CodigoSucursalField;
            }
            set
            {
                this.CodigoSucursalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ContadorMovimientos
        {
            get
            {
                return this.ContadorMovimientosField;
            }
            set
            {
                this.ContadorMovimientosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion
        {
            get
            {
                return this.FechaCreacionField;
            }
            set
            {
                this.FechaCreacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Saldo
        {
            get
            {
                return this.SaldoField;
            }
            set
            {
                this.SaldoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DepositoResultDTO", Namespace= "http://schemas.datacontract.org/2004/07/EurekaBank_Soap_DotNet_GR05.Models.DTOs")]
    public partial class DepositoResultDTO : object
    {
        
        private decimal ImporteField;
        
        private int NumeroMovimientoField;
        
        private decimal SaldoAnteriorField;
        
        private decimal SaldoNuevoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Importe
        {
            get
            {
                return this.ImporteField;
            }
            set
            {
                this.ImporteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroMovimiento
        {
            get
            {
                return this.NumeroMovimientoField;
            }
            set
            {
                this.NumeroMovimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SaldoAnterior
        {
            get
            {
                return this.SaldoAnteriorField;
            }
            set
            {
                this.SaldoAnteriorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SaldoNuevo
        {
            get
            {
                return this.SaldoNuevoField;
            }
            set
            {
                this.SaldoNuevoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetiroResultDTO", Namespace= "http://schemas.datacontract.org/2004/07/EurekaBank_Soap_DotNet_GR05.Models.DTOs")]
    public partial class RetiroResultDTO : object
    {
        
        private decimal CostoPorMovimientoField;
        
        private decimal ITFField;
        
        private decimal ImporteRetiroField;
        
        private decimal SaldoAnteriorField;
        
        private decimal SaldoNuevoField;
        
        private decimal TotalDescontadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CostoPorMovimiento
        {
            get
            {
                return this.CostoPorMovimientoField;
            }
            set
            {
                this.CostoPorMovimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ITF
        {
            get
            {
                return this.ITFField;
            }
            set
            {
                this.ITFField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ImporteRetiro
        {
            get
            {
                return this.ImporteRetiroField;
            }
            set
            {
                this.ImporteRetiroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SaldoAnterior
        {
            get
            {
                return this.SaldoAnteriorField;
            }
            set
            {
                this.SaldoAnteriorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SaldoNuevo
        {
            get
            {
                return this.SaldoNuevoField;
            }
            set
            {
                this.SaldoNuevoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalDescontado
        {
            get
            {
                return this.TotalDescontadoField;
            }
            set
            {
                this.TotalDescontadoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransferenciaResultDTO", Namespace= "http://schemas.datacontract.org/2004/07/EurekaBank_Soap_DotNet_GR05.Models.DTOs")]
    public partial class TransferenciaResultDTO : object
    {
        
        private decimal CostoPorMovimientoField;
        
        private DotNetSoapTransaction.CuentaResumenDTO CuentaDestinoField;
        
        private DotNetSoapTransaction.CuentaResumenDTO CuentaOrigenField;
        
        private decimal ITFField;
        
        private decimal ImporteTransferidoField;
        
        private decimal TotalDescontadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CostoPorMovimiento
        {
            get
            {
                return this.CostoPorMovimientoField;
            }
            set
            {
                this.CostoPorMovimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DotNetSoapTransaction.CuentaResumenDTO CuentaDestino
        {
            get
            {
                return this.CuentaDestinoField;
            }
            set
            {
                this.CuentaDestinoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DotNetSoapTransaction.CuentaResumenDTO CuentaOrigen
        {
            get
            {
                return this.CuentaOrigenField;
            }
            set
            {
                this.CuentaOrigenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ITF
        {
            get
            {
                return this.ITFField;
            }
            set
            {
                this.ITFField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ImporteTransferido
        {
            get
            {
                return this.ImporteTransferidoField;
            }
            set
            {
                this.ImporteTransferidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalDescontado
        {
            get
            {
                return this.TotalDescontadoField;
            }
            set
            {
                this.TotalDescontadoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CuentaResumenDTO", Namespace= "http://schemas.datacontract.org/2004/07/EurekaBank_Soap_DotNet_GR05.Models.DTOs")]
    public partial class CuentaResumenDTO : object
    {
        
        private string CodigoField;
        
        private decimal SaldoAnteriorField;
        
        private decimal SaldoNuevoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SaldoAnterior
        {
            get
            {
                return this.SaldoAnteriorField;
            }
            set
            {
                this.SaldoAnteriorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SaldoNuevo
        {
            get
            {
                return this.SaldoNuevoField;
            }
            set
            {
                this.SaldoNuevoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransferenciaDTO", Namespace= "http://schemas.datacontract.org/2004/07/EurekaBank_Soap_DotNet_GR05.Models.DTOs")]
    public partial class TransferenciaDTO : object
    {
        
        private string ClaveCuentaOrigenField;
        
        private string CodigoEmpleadoField;
        
        private string CuentaDestinoField;
        
        private string CuentaOrigenField;
        
        private decimal ImporteField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaveCuentaOrigen
        {
            get
            {
                return this.ClaveCuentaOrigenField;
            }
            set
            {
                this.ClaveCuentaOrigenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoEmpleado
        {
            get
            {
                return this.CodigoEmpleadoField;
            }
            set
            {
                this.CodigoEmpleadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CuentaDestino
        {
            get
            {
                return this.CuentaDestinoField;
            }
            set
            {
                this.CuentaDestinoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CuentaOrigen
        {
            get
            {
                return this.CuentaOrigenField;
            }
            set
            {
                this.CuentaOrigenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Importe
        {
            get
            {
                return this.ImporteField;
            }
            set
            {
                this.ImporteField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DotNetSoapTransaction.IServicioTransaccion")]
    public interface IServicioTransaccion
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTransaccion/RealizarDeposito", ReplyAction="http://tempuri.org/IServicioTransaccion/RealizarDepositoResponse")]
        System.Threading.Tasks.Task<DotNetSoapTransaction.RespuestaDTO> RealizarDepositoAsync(DotNetSoapTransaction.TransaccionDTO datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTransaccion/RealizarRetiro", ReplyAction="http://tempuri.org/IServicioTransaccion/RealizarRetiroResponse")]
        System.Threading.Tasks.Task<DotNetSoapTransaction.RespuestaDTO> RealizarRetiroAsync(DotNetSoapTransaction.TransaccionDTO datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTransaccion/RealizarTransferencia", ReplyAction="http://tempuri.org/IServicioTransaccion/RealizarTransferenciaResponse")]
        System.Threading.Tasks.Task<DotNetSoapTransaction.RespuestaDTO> RealizarTransferenciaAsync(DotNetSoapTransaction.TransferenciaDTO datos);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IServicioTransaccionChannel : DotNetSoapTransaction.IServicioTransaccion, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ServicioTransaccionClient : System.ServiceModel.ClientBase<DotNetSoapTransaction.IServicioTransaccion>, DotNetSoapTransaction.IServicioTransaccion
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioTransaccionClient() : 
                base(ServicioTransaccionClient.GetDefaultBinding(), ServicioTransaccionClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioTransaccion.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioTransaccionClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioTransaccionClient.GetBindingForEndpoint(endpointConfiguration), ServicioTransaccionClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioTransaccionClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioTransaccionClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioTransaccionClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioTransaccionClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioTransaccionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<DotNetSoapTransaction.RespuestaDTO> RealizarDepositoAsync(DotNetSoapTransaction.TransaccionDTO datos)
        {
            return base.Channel.RealizarDepositoAsync(datos);
        }
        
        public System.Threading.Tasks.Task<DotNetSoapTransaction.RespuestaDTO> RealizarRetiroAsync(DotNetSoapTransaction.TransaccionDTO datos)
        {
            return base.Channel.RealizarRetiroAsync(datos);
        }
        
        public System.Threading.Tasks.Task<DotNetSoapTransaction.RespuestaDTO> RealizarTransferenciaAsync(DotNetSoapTransaction.TransferenciaDTO datos)
        {
            return base.Channel.RealizarTransferenciaAsync(datos);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioTransaccion))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioTransaccion))
            {
                return new System.ServiceModel.EndpointAddress("http://10.40.16.33:8004/ws/ServicioTransaccion.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioTransaccionClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioTransaccion);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioTransaccionClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioTransaccion);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioTransaccion,
        }
    }
}
